_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'clevrtex' 
  IMG_SIZE: 128
OUTPUT:
  DIR: './output_dir/ARK_conv_clvt/'
TRAIN:
  OPTIMIZER: 'adam'
MODEL:
  SLOT:
    NUM: 11
    ATTN_SMOOTH: "conv"