_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'clevrtex' 
  IMG_SIZE: 128
OUTPUT:
  DIR: './output_dir/ARK_gaussian_clvt/'
TRAIN:
  OPTIMIZER: 'adam'
MODEL:
  SLOT:
    NUM: 11
    ATTN_SMOOTH: "gaussian"
    ATTN_SMOOTH_GAU_MIN: 0.1
    ATTN_SMOOTH_GAU_MAX: 2.0