_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'clevrtex' 
  IMG_SIZE: 128
OUTPUT:
  DIR: './output_dir/IPPE_1.0_1.0_clvt/'
TRAIN:
  EPOCHS: 800
  BATCH_SIZE: 256
  POS_LOSS_WEIGHT: 0.01
WEAK_SUP:
  TYPE: "bbox_center"
  RANDOM_PROP: 1.0
  INIT_USING_SUP: False
  SPLIT:
    RATIO: 1.0
POS_PRED:
  USE_POS_PRED: True
  USE_GT: True
MODEL:
  SLOT:
    NUM: 11